# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

# перед тем как запустить rake db:seeds
# нужно пересоздать некоторые таблицы из базы данных
# а именно - locations, product_categories, product_sections, product_sub_sections
# для этого делаем так
# rake db:migrate:down VERSION=20120114155748
# rake db:migrate:down VERSION=20120114130832
# rake db:migrate:down VERSION=20120114133909
# rake db:migrate:down VERSION=20120114151018
# rake db:migrate:up VERSION=20120114155748
# rake db:migrate:up VERSION=20120114130832
# rake db:migrate:up VERSION=20120114133909
# rake db:migrate:up VERSION=20120114151018
# или всё за один раз:
# rake db:migrate:down VERSION=20120114155748 ; rake db:migrate:down VERSION=20120114130832 ; rake db:migrate:down VERSION=20120114133909 ; rake db:migrate:down VERSION=20120114151018 ; rake db:migrate:up VERSION=20120114155748 ; rake db:migrate:up VERSION=20120114130832 ; rake db:migrate:up VERSION=20120114133909 ; rake db:migrate:up VERSION=20120114151018

Location.create( :name => 'Тихорецк', :form => 'город' )
Location.create( :name => 'Кропоткин', :form => 'город' )
Location.create( :name => 'Новороссийск', :form => 'город' )
Location.create( :name => 'Краснодар', :form => 'город' )
Location.create( :name => 'Усть-Лабинск', :form => 'город' )

n = ProductCategory.create( :category => 'Недвижимость' )
s = ProductSection.create(    :section => 'Квартиры', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Новостройки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Комнаты', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => '1 комнатные', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => '2-х комнатные', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => '3-х и более комнатные', :product_category_id => n.id, :product_section_id => s.id ) 
s = ProductSection.create(    :section => 'Домовладения', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'до 50 м²', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'до 100 м²', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => 'до 150 м²', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'до 300 м²', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => 'свыше 300 м²', :product_category_id => n.id, :product_section_id => s.id )    
s = ProductSection.create(    :section => 'Участки, дачи, гаражи', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Участки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Дачи', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => 'Гаражи', :product_category_id => n.id, :product_section_id => s.id ) 
s = ProductSection.create(    :section => 'Комерческая', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Магазины', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Офисы', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => 'Склады', :product_category_id => n.id, :product_section_id => s.id ) 
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )                                   
s = ProductSection.create(    :section => 'Аренда', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Квартиры', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Домовладения', :product_category_id => n.id, :product_section_id => s.id )                                
  ProductSubSection.create(     :subsection => 'Гаражи', :product_category_id => n.id, :product_section_id => s.id ) 
  ProductSubSection.create(     :subsection => 'Офисы', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Магазины', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Склады', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )

n = ProductCategory.create( :category => 'Транспорт' )
s = ProductSection.create(    :section => 'Легковые', :product_category_id => n.id )
s = ProductSection.create(    :section => 'Грузовые, автобусы, спец. техника', :product_category_id => n.id )
s = ProductSection.create(    :section => 'Мотоциклы, снегоходы', :product_category_id => n.id )
s = ProductSection.create(    :section => 'Водный транспорт', :product_category_id => n.id )
s = ProductSection.create(    :section => 'Автозапчасти и аксессуары', :product_category_id => n.id )

n = ProductCategory.create( :category => 'Предметы быта' )
s = ProductSection.create(    :section => 'Электроника', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Компьютеры и комплектующие', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Ноутбуки, аксесуары', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Планшетные ПК, электронные книги, КПК', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Телефоны', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Фототехника', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Игровые приставки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Бытовая техника', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Холодильники', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'СВЧ печи', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Газовые печи, вытяжки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Посудомоечные машины', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Климатические системы', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Пылесосы', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Одежда и обувь', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Женская одежда и обувь', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Мужская одежда и обувь', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Ремонт/пошив одежды, обуви', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Для детей', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Кроватки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Коляски', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Игрушки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Продукты', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Одежда', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Мебель', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Столы, стулья', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Стенки, шкафы', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Кухонная мебель', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Диваны, кровати, кресла', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Украшения и подарки', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Бижутерия', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Золото, серебро', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Антиквариат, нумизматика', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Посуда, фарфор, хрусталь', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Отдам даром', :product_category_id => n.id )

n = ProductCategory.create( :category => 'Услуги' )
s = ProductSection.create(    :section => 'Юридические', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Защита прав', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Представительство интересов в суде', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Сопровождение сделок', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Красота и здоровье', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Наращивание ногтей', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Наращивание волос', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Парикмахерские', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Косметологические услуги', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Ищу/предлагаю работу', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Ищу работу', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Предлагаю работу', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Строительство', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Фундамент, стены', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Штукатурка, стяжка', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Крыша, окна', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Отделка дизайн', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Инструмент, крепёж', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Видео-фото съёмка', :product_category_id => n.id )

n = ProductCategory.create( :category => 'Разное' )
s = ProductSection.create(    :section => 'Домашние животные', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Кошки, собаки', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Птицы', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Другие животные', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Корма', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Личное подсобное хозяйство', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Птица, яйца, молоко', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Мясо, шкуры', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Фрукты, овощи', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Корма', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )
s = ProductSection.create(    :section => 'Развлечения', :product_category_id => n.id )
  ProductSubSection.create(     :subsection => 'Экскурсии', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Праздники', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Активный отдых', :product_category_id => n.id, :product_section_id => s.id )
  ProductSubSection.create(     :subsection => 'Прочее', :product_category_id => n.id, :product_section_id => s.id )

